#! /bin/sh
# Copyright 2017 Martin C. Frith

maf=$1

shift || {
    cat <<EOF
Usage: $0 pairwise-alignments.maf sequences.fasta > out.fasta

Get the FASTA sequences whose names appear in bottom MAF lines.
EOF
    exit
}

sed 's/^>/> /' "$@" |

awk '
BEGIN {while (getline < "'"$maf"'") if (/^s/ && s++ % 2) a[$2] = 1}
/^>/ {i = $2 in a} i
' |

sed 's/^> />/'
